version: "3.8"

services:
  pass:
    image: pass:latest
    ports:
      - 80:3000
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://dokploy:amukds4wi9001583845717ad2@postgres:5432/dokploy
      REDIS_URL: redis://redis:6379
      IS_CLOUD: true
      
  postgres:
    image: docker.arvancloud.ir/bitnami/postgresql:13
    container_name: postgres
    environment:
      POSTGRESQL_USERNAME: dokploy
      POSTGRESQL_PASSWORD: amukds4wi9001583845717ad2
      POSTGRESQL_DATABASE: dokploy
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: docker.arvancloud.ir/redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
